# Generated by Django 3.1.7 on 2021-04-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapbookmark', '0003_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
