# Generated by Django 3.1.7 on 2021-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapbookmark', '0004_auto_20210407_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='content',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='marker',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
