# Generated by Django 3.1.7 on 2021-04-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapbookmark', '0005_auto_20210408_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='address_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
